import { createOpenAI } from "@ai-sdk/openai";
import { streamText } from "ai";
import { Hono } from "hono";

// Global Env is auto-generated by `pnpm cf-typegen` from wrangler.toml [vars]
const app = new Hono<{ Bindings: Env }>();

// ── Types for Assistant-UI wire format ────────────────────────────────────────

type MessagePart =
	| { type: "text"; text: string }
	| { type: "image"; image?: string; url?: string }
	| { type: "image_url"; image_url?: { url: string }; url?: string }
	| { type: "file"; mediaType?: string; url?: string };

type UIMessage = {
	role: string;
	parts?: MessagePart[];
	content?: string;
};

/** Convert Assistant-UI UIMessage parts → Vercel AI SDK CoreMessage content array. */
function toCoreParts(parts: MessagePart[]) {
	return parts
		.map((p) => {
			if (p.type === "text") return { type: "text" as const, text: p.text };
			if (p.type === "image")
				return { type: "image" as const, image: p.image ?? p.url ?? "" };
			if (p.type === "image_url")
				return {
					type: "image" as const,
					image: p.image_url?.url ?? p.url ?? "",
				};
			if (p.type === "file")
				return {
					type: "file" as const,
					mimeType: p.mediaType ?? "application/octet-stream",
					data: p.url ?? "",
				};
			return null;
		})
		.filter(Boolean);
}

// ── Routes ────────────────────────────────────────────────────────────────────

app.get("/api/health", (c) => c.json({ status: "ok", name: "roast-prof" }));

app.post("/api/chat", async (c) => {
	try {
		const { messages } = await c.req.json<{ messages: UIMessage[] }>();

		if (!c.env.API_KEY) return c.json({ error: "Missing API_KEY secret" }, 500);
		if (!c.env.MODEL) return c.json({ error: "Missing MODEL env var" }, 500);

		const provider = createOpenAI({
			baseURL: c.env.BASE_URL,
			apiKey: c.env.API_KEY,
			// Simulate request origin for OpenRouter routing & analytics
			headers: {
				"HTTP-Referer": c.env.SITE_URL,
				"X-OpenRouter-Title": c.env.SITE_NAME,
				"X-OpenRouter-Categories": c.env.SITE_CATEGORIES,
			},
			fetch,
		});

		const coreMessages = messages.map((m) => ({
			role: m.role,
			content: m.parts?.length
				? toCoreParts(m.parts as MessagePart[])
				: (m.content ?? ""),
		}));

		console.log(`[Worker] ${messages.length} msgs → ${c.env.MODEL}`);

		const result = streamText({
			model: provider.chat(c.env.MODEL),
			// biome-ignore lint/suspicious/noExplicitAny: CoreMessage union doesn't express mixed role+content at compile time
			messages: coreMessages as any,
			system:
				"你现在是林亦频道的「暴躁教授」。用极其刻薄、但也足够专业的学术口吻回答问题。偶尔嘲讽用户的无知，偶尔冷幽默。保持中文，短句为主。",
		});

		return result.toUIMessageStreamResponse();
	} catch (error: unknown) {
		const msg = error instanceof Error ? error.message : "Unknown error";
		console.error("[Worker] /api/chat error:", msg);
		return c.json({ error: msg }, 500);
	}
});

export default app;
