import { createOpenAI } from "@ai-sdk/openai";
import { extractReasoningMiddleware, streamText, wrapLanguageModel } from "ai";
import { Hono } from "hono";

// Global Env is auto-generated by `pnpm cf-typegen` from wrangler.toml [vars]
const app = new Hono<{ Bindings: Env }>();

// ── Assistant-UI wire format types ───────────────────────────────────────────

type MessagePart =
	| { type: "text"; text: string }
	| { type: "image"; image?: string; url?: string }
	| { type: "image_url"; image_url?: { url: string }; url?: string }
	| { type: "file"; mediaType?: string; url?: string; name?: string };

type UIMessage = {
	role: string;
	parts?: MessagePart[];
	content?: string;
};

// ── OpenRouter format builders ───────────────────────────────────────────────
// Reference: https://openrouter.ai/docs/guides/overview/multimodal/overview

type OpenRouterContentPart =
	| { type: "text"; text: string }
	| { type: "image_url"; image_url: { url: string } }
	| { type: "file"; file: { filename: string; file_data: string } }
	| { type: "input_audio"; input_audio: { data: string; format: string } }
	| { type: "video_url"; video_url: { url: string } };

/** Extract raw base64 from a data URL (strips the data:mime;base64, header). */
function extractBase64(dataUrl: string): string {
	const idx = dataUrl.indexOf(",");
	return idx >= 0 ? dataUrl.slice(idx + 1) : dataUrl;
}

/** Convert a single AssistantUI MessagePart → OpenRouter wire format. */
function toOpenRouterPart(p: MessagePart): OpenRouterContentPart | null {
	if (p.type === "text") return { type: "text", text: p.text };

	if (p.type === "image" || p.type === "image_url") {
		const url =
			p.type === "image_url"
				? (p.image_url?.url ?? p.url ?? "")
				: (p.image ?? p.url ?? "");
		return { type: "image_url", image_url: { url } };
	}

	if (p.type === "file") {
		const url = p.url ?? "";
		const mime = p.mediaType ?? "application/octet-stream";
		const filename = p.name ?? `attachment.${mime.split("/")[1] ?? "bin"}`;

		if (mime.startsWith("image/"))
			return { type: "image_url", image_url: { url } };
		if (mime === "application/pdf")
			return { type: "file", file: { filename, file_data: url } };
		if (mime.startsWith("audio/"))
			return {
				type: "input_audio",
				input_audio: {
					data: extractBase64(url),
					format: mime.split("/")[1] ?? "wav",
				},
			};
		if (mime.startsWith("video/"))
			return { type: "video_url", video_url: { url } };
	}

	return null;
}

/** Build complete OpenRouter messages array (system + conversation). */
function buildOpenRouterMessages(
	uiMessages: UIMessage[],
	systemPrompt: string,
): Array<{ role: string; content: string | OpenRouterContentPart[] }> {
	const result: Array<{
		role: string;
		content: string | OpenRouterContentPart[];
	}> = [{ role: "system", content: systemPrompt }];

	for (const m of uiMessages) {
		if (m.parts?.length) {
			const parts = m.parts
				.map(toOpenRouterPart)
				.filter((p): p is OpenRouterContentPart => p !== null);
			result.push({ role: m.role, content: parts });
		} else {
			result.push({ role: m.role, content: m.content ?? "" });
		}
	}
	return result;
}

// ── SSE streaming transform ───────────────────────────────────────────────────
// OpenRouter returns `delta.reasoning` for reasoning models.
// The easiest way for Vercel AI SDK to pick this up is to inject the content into
// `<think>...</think>` tags and use `extractReasoningMiddleware`.

function transformReasoningSSE(response: Response): Response {
	if (!response.body) return response;

	const encoder = new TextEncoder();
	const decoder = new TextDecoder();
	let buffer = "";
	let inReasoning = false;

	const transform = new TransformStream<Uint8Array, Uint8Array>({
		transform(chunk, controller) {
			buffer += decoder.decode(chunk, { stream: true });
			const lines = buffer.split("\n");
			buffer = lines.pop() ?? "";

			for (const line of lines) {
				if (!line.startsWith("data: ")) {
					controller.enqueue(encoder.encode(`${line}\n`));
					continue;
				}
				const data = line.slice(6).trim();

				if (data === "[DONE]") {
					if (inReasoning) {
						const closing = { choices: [{ delta: { content: "</think>" } }] };
						controller.enqueue(
							encoder.encode(`data: ${JSON.stringify(closing)}\n`),
						);
						inReasoning = false;
					}
					controller.enqueue(encoder.encode(`${line}\n`));
					continue;
				}

				try {
					const json = JSON.parse(data);
					let modified = false;

					if (Array.isArray(json.choices)) {
						for (const choice of json.choices) {
							if (choice.delta?.reasoning !== undefined) {
								let contentInjection = "";
								if (!inReasoning) {
									contentInjection += "<think>";
									inReasoning = true;
								}
								contentInjection += choice.delta.reasoning;

								choice.delta.content =
									(choice.delta.content || "") + contentInjection;
								delete choice.delta.reasoning;
								modified = true;
							} else if (
								inReasoning &&
								(choice.delta?.content !== undefined || choice.finish_reason)
							) {
								// End of reasoning segment
								choice.delta = choice.delta || {};
								choice.delta.content = `</think>${choice.delta.content || ""}`;
								inReasoning = false;
								modified = true;
							}
						}
					}

					if (modified || (json.choices && json.choices.length > 0)) {
						controller.enqueue(
							encoder.encode(`data: ${JSON.stringify(json)}\n`),
						);
					} else {
						controller.enqueue(encoder.encode(`${line}\n`));
					}
				} catch {
					controller.enqueue(encoder.encode(`${line}\n`));
				}
			}
		},
		flush(controller) {
			if (inReasoning) {
				const closing = { choices: [{ delta: { content: "</think>" } }] };
				controller.enqueue(
					encoder.encode(`data: ${JSON.stringify(closing)}\n`),
				);
			}
			if (buffer) controller.enqueue(encoder.encode(buffer));
		},
	});

	return new Response(response.body.pipeThrough(transform), {
		status: response.status,
		statusText: response.statusText,
		headers: response.headers,
	});
}

// ── Routes ────────────────────────────────────────────────────────────────────

app.get("/api/health", (c) => c.json({ status: "ok" }));

app.post("/api/chat", async (c) => {
	try {
		const { messages } = await c.req.json<{ messages: UIMessage[] }>();

		if (!c.env.API_KEY) return c.json({ error: "Missing API_KEY secret" }, 500);
		if (!c.env.MODEL) return c.json({ error: "Missing MODEL env var" }, 500);

		const systemPrompt =
			c.env.SYSTEM_PROMPT || "You are a helpful and clear AI assistant.";

		const openRouterMessages = buildOpenRouterMessages(messages, systemPrompt);
		const model = c.env.MODEL;

		const isMultimodal = messages.some((m) =>
			m.parts?.some((p) => p.type !== "text"),
		);
		console.log(
			`[Worker] ${messages.length} msgs → ${model} (multimodal: ${isMultimodal})`,
		);

		const provider = createOpenAI({
			baseURL: c.env.BASE_URL,
			apiKey: c.env.API_KEY,
			headers: {
				"HTTP-Referer": c.env.SITE_URL,
				"X-OpenRouter-Title": c.env.SITE_NAME,
				"X-OpenRouter-Categories": c.env.SITE_CATEGORIES,
			},
			fetch: async (url, options) => {
				// Inject OpenRouter-formatted messages
				const body = JSON.parse((options as RequestInit).body as string);
				body.messages = openRouterMessages;
				const raw = await fetch(url as string, {
					...(options as RequestInit),
					body: JSON.stringify(body),
				});
				// Map delta.reasoning → <think>...</think> for SDK recognition
				return transformReasoningSSE(raw);
			},
		});

		const wrappedModel = wrapLanguageModel({
			model: provider.chat(model),
			middleware: extractReasoningMiddleware({ tagName: "think" }),
		});

		const result = streamText({
			model: wrappedModel,
			messages: [{ role: "user", content: "." }], // placeholder — real messages injected via fetch
		});

		return result.toUIMessageStreamResponse();
	} catch (error: unknown) {
		const msg = error instanceof Error ? error.message : "Unknown error";
		console.error("[Worker] /api/chat error:", msg);
		return c.json({ error: msg }, 500);
	}
});

export default app;
